use_frameworks!

platform :ios, '13.0'

target 'StikerFace_Example' do
  pod 'StickerFaceEditor', :git => 'git@github.com:sflabsorg/stickerfaceeditor-ios.git', :commit => 'abe6792'
  pod 'StikerFace', :path => '../'

end
